build:
  image: clickable/ci-16.04-armhf
  script:
    - clickable --output ./build build-libs qtdbusextended
    - clickable --output ./build build-libs nemo-qml-plugin-dbus
    - clickable --output ./build build-libs qtmpris
    - clickable --output ./build build-libs qmdnsengine
    - clickable --output ./build build
  artifacts:
    paths:
      - build/*.click
    expire_in: never

build64:
  image: clickable/ci-16.04-arm64
  script:
    - clickable --output ./build64 build-libs qtdbusextended --arch arm64
    - clickable --output ./build64 build-libs nemo-qml-plugin-dbus --arch arm64
    - clickable --output ./build64 build-libs qtmpris --arch arm64
    - clickable --output ./build64 build-libs qmdnsengine --arch arm64
    - clickable --output ./build64 build --arch arm64
  artifacts:
    paths:
      - build64/*.click
    expire_in: never
